#!/bin/bash

mkdir -p /tmp/seamless-database

SEAMLESS_IMG=docker://rpbs/seamless  # will always work
#SEAMLESS_IMG=/tmp/images/rpbs/seamless.simg  # laptop
#SEAMLESS_IMG=/scratch/software/singularity/images # RPBS cluster

singularity exec ${SEAMLESS_IMG} \
  python3 -u /home/jovyan/seamless-tools/database.py \
  database-minimal.yaml